In [2]:
import numpy as np

In [4]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [5]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [15]:
y[0]

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [12]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [19]:
b = y>20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [18]:
y[y>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [21]:
b[:,5]

array([False, False, False,  True,  True])

In [22]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [4]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [7]:
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]
row_vec

array([[0, 1, 2, 3]])

In [8]:
# make it as column vector by inserting an axis along second dimension
row_vec = arr[:, np.newaxis]
row_vec

array([[0],
       [1],
       [2],
       [3]])