In [1]:
import numpy as np

### Array Creation

In [20]:
a = np.array([2, 3, 4, 5])
a

array([2, 3, 4, 5])

In [21]:
b = np.array([(1, 2, 3), (4, 5, 6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros([2, 3, 4], dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

### Conversion from 1D to 2D, 3D

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [33]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Indexing, Slicing and Iterating

In [35]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [37]:
a[2:5]

array([ 8, 27, 64])

In [41]:
a[:6:2] = -100
a

array([-100,    1, -100,   27, -100,  125,  216,  343,  512,  729])

In [46]:
a[ : : -1]

array([ 729,  512,  343,  216,  125, -100,   27, -100,    1, -100])

In [47]:
b = np.fromfunction(lambda x, y: 10*x+y, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [48]:
b[2, 3]

23

In [51]:
# b[:, 1]
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [54]:
b[-1,] # last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

In [57]:
c = np.array([[[  0,   1,  2],
               [ 10,  12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [58]:
c.shape

(2, 2, 3)

In [66]:
c[1, ...] # c[1, :, :]

array([[100, 101, 102],
       [110, 112, 113]])

In [67]:
c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [68]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [69]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape Manipulation

In [80]:
a = np.floor(10*np.random.random((3, 4)))
a

array([[1., 6., 8., 7.],
       [6., 0., 8., 4.],
       [4., 0., 4., 2.]])

In [81]:
a.shape

(3, 4)

In [85]:
a.ravel() # returns the array flattened

array([1., 6., 8., 7., 6., 0., 8., 4., 4., 0., 4., 2.])

In [88]:
a.resize(2, 6) # resize modifies the array itself
a

array([[1., 6., 8., 7., 6., 0.],
       [8., 4., 4., 0., 4., 2.]])

### Stacking together different arrays

In [97]:
a = np.floor(10 * np.random.random([2, 2]))
a

array([[5., 2.],
       [0., 4.]])

In [98]:
b = np.floor(10 * np.random.random([2, 2]))
b

array([[7., 1.],
       [9., 0.]])

In [99]:
np.vstack((a, b))

array([[5., 2.],
       [0., 4.],
       [7., 1.],
       [9., 0.]])

In [100]:
np.hstack((a, b))

array([[5., 2., 7., 1.],
       [0., 4., 9., 0.]])

### column_stack stacks 1D arrays as columns into a 2D array

In [101]:
np.column_stack((a, b)) # with 2D arrays

array([[5., 2., 7., 1.],
       [0., 4., 9., 0.]])

In [102]:
a = np.array([4, 2])

In [103]:
b = np.array([3, 8])

In [105]:
np.column_stack((a, b)) # returns a 2D array

array([[4, 3],
       [2, 8]])

In [106]:
np.hstack((a, b))

array([4, 2, 3, 8])

In [109]:
a[:, np.newaxis]

array([[4],
       [2]])

In [110]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4, 3],
       [2, 8]])

In [112]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis])) # result is same

array([[4, 3],
       [2, 8]])