In [1]:
import numpy as np

### rand(d0, d1, ..., dn)
Random values in a given shape.

In [7]:
np.random.rand()

0.08923191740587988

In [17]:
a = np.random.rand(3, 4)
print(a)

[[0.12364421 0.92119417 0.01977332 0.0180424 ]
 [0.92873579 0.66529678 0.01786404 0.83613377]
 [0.76472234 0.90122516 0.3344215  0.97219222]]


### randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.

In [27]:
a = np.random.randn(2, 3)
print(a)

[[ 0.38356067 -1.55691682 -0.55046766]
 [ 0.25253107  0.27218172 -0.7956834 ]]


### randint(low, high=None, size=None, dtype='l')
Return random integers from [low, high)

If high is None (the default), then results are from [0, low)

In [24]:
a = np.random.randint(3, size=10)
print(a)

[2 1 1 1 1 1 0 0 2 1]


In [25]:
a = np.random.randint(3, size=(2, 4))
print(a)

[[2 1 2 2]
 [2 1 1 1]]


### random_sample(size=None)
### random(size=None)
Return random floats in the half-open interval [0.0, 1.0)

In [33]:
a = np.random.random_sample((5,))
print(a)

[0.55052749 0.29468981 0.6946704  0.93373997 0.92628213]


In [36]:
# sample between [a, b)
# (b - a) * random_sample() + a

# sample between [5, 10)
a = (10 - 5) * np.random.random_sample(7,) + 5
print(a)

[7.02183461 5.66218267 9.66645843 9.78029999 9.52477542 8.09984155
 6.04904237]


### uniform(low=0.0, high=1.0, size=None)
Draw samples from a uniform distribution

In [54]:
a = np.random.uniform(0, 1, 10)
print(a)

[0.92992188 0.13533813 0.25383691 0.12597926 0.72835214 0.78898326
 0.05810718 0.52693693 0.1113868  0.71623994]
