In [1]:
import numpy as np

### split(ary, indices_or_sections, axis=0)
Split an array into multiple sub-arrays

In [91]:
x = np.arange(9)
print (x.shape)

(9,)


In [93]:
out = np.split(x, 3)
print (out[0].shape)
print (out)

(3,)
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [7]:
x = np.arange(8)

In [8]:
np.split(x, [3, 5, 6, 10])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int64)]

In [124]:
x = np.arange(48).reshape(2, 4, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [125]:
out = np.split(x, 2, axis=0)
print (out[0].shape)
print (out)

(1, 4, 6)
[array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]]), array([[[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])]


In [126]:
out = np.split(x, 2, axis=1)
print (out[0].shape)
print (out)

(2, 2, 6)
[array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]]), array([[[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])]


In [127]:
out = np.split(x, 2, axis=2)
print (out[0].shape)
print (out)

(2, 4, 3)
[array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[24, 25, 26],
        [30, 31, 32],
        [36, 37, 38],
        [42, 43, 44]]]), array([[[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]],

       [[27, 28, 29],
        [33, 34, 35],
        [39, 40, 41],
        [45, 46, 47]]])]


### array_split(ary, indices_or_sections, axis=0)
Split an array into multiple sub-arrays

difference between split and array_split functions is that array_split allows indices_or_sections to be an integer that does not equally divide the axis. For an array of length l that should be split into n sections, it returns l % n sub-arrays of size l//n + 1 and the rest of size l//n.

In [9]:
x = np.arange(8)

In [10]:
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [12]:
x = np.arange(7)

In [13]:
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

### dsplit(ary, indices_or_sections)
Split array into multiple sub-arrays along the 3rd axis (depth).

dsplit is equivalent to split with axis=2, the array is always split along the third axis provided the array dimension is greater than or equal to 3

In [128]:
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [129]:
out = np.dsplit(x, 2)
print (out[0].shape)
print (out)

(2, 3, 2)
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [120]:
out = np.dsplit(x, np.array([2, 3]))
print (out[0].shape)
print (out)

(2, 3, 2)
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]


### hsplit(ary, indices_or_sections)
Split an array into multiple sub-arrays horizontally (column-wise).

hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension

In [130]:
x = np.arange(16).reshape(2, 2, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [131]:
out = np.hsplit(x, 2)
print (out[0].shape)
print (out)

(2, 1, 4)
[array([[[ 0,  1,  2,  3]],

       [[ 8,  9, 10, 11]]]), array([[[ 4,  5,  6,  7]],

       [[12, 13, 14, 15]]])]


In [105]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [106]:
out = np.hsplit(x, 2)
print (out[0].shape)
print (out)

(4, 2)
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


### vsplit(ary, indices_or_sections)
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the split documentation. vsplit is equivalent to split with axis=0 (default), the array is always split along the first axis regardless of the array dimension.

In [141]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [142]:
out = np.vsplit(x, 2)
print (out[0].shape)
print (out)

(2, 4)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [143]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [144]:
x = np.arange(16).reshape(2, 2, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [145]:
out = np.vsplit(x, 2)
print (out[0].shape)
print (out)

(1, 2, 4)
[array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]]), array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])]
