In [2]:
import numpy as np

### Stack(arrays, axis=0, out=None)
Stack a sequence of arrays along a new axis.

The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

In [74]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
#arrays = [np.random.randint(3, size=(3, 4)) for _ in range(10)]
#for array in arrays:
#    print (array)

In [75]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [76]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [77]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [60]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print (a.shape)

(3,)


In [53]:
print (np.stack((a, b)).shape)
np.stack((a, b))

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
print (np.stack((a, b), axis=1).shape)
#np.stack((a, b), axis=-1)
np.stack((a, b), axis=1)

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [13]:
print (np.stack((a, b)).shape)
np.stack((a, b))

(2, 3, 4)


array([[[100, 101, 102, 103],
        [110, 111, 112, 113],
        [120, 121, 122, 123]],

       [[200, 201, 202, 203],
        [210, 211, 212, 213],
        [220, 221, 222, 223]]])

In [14]:
print (np.stack((a, b), axis=1).shape)
np.stack((a, b), axis=1)

(3, 2, 4)


array([[[100, 101, 102, 103],
        [200, 201, 202, 203]],

       [[110, 111, 112, 113],
        [210, 211, 212, 213]],

       [[120, 121, 122, 123],
        [220, 221, 222, 223]]])

In [17]:
print (np.stack((a, b), axis=2).shape)
np.stack((a, b), axis=2)

(3, 4, 2)


array([[[100, 200],
        [101, 201],
        [102, 202],
        [103, 203]],

       [[110, 210],
        [111, 211],
        [112, 212],
        [113, 213]],

       [[120, 220],
        [121, 221],
        [122, 222],
        [123, 223]]])

### concatenate((a1, a2, ...), axis=0, out=None)
Join a sequence of arrays along an existing axis

In [93]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print (a.shape)

(3,)


In [94]:
out = np.concatenate((a, b), axis=0)
print(out.shape)
out

(6,)


array([1, 2, 3, 4, 5, 6])

In [79]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print (a)
print (b)
print (a.shape)
print (b.shape)

[[1 2]
 [3 4]]
[[5 6]]
(2, 2)
(1, 2)


In [46]:
out = np.concatenate((a, b), axis=0)
print(out.shape)
out

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
out = np.concatenate((a, b.T), axis=1)
print(out.shape)
out

(2, 3)


array([[1, 2, 5],
       [3, 4, 6]])

In [96]:
out = np.concatenate((a, b), axis=None)
print(out.shape)
out

(6,)


array([1, 2, 3, 4, 5, 6])

In [103]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [105]:
out = np.concatenate((a, b), axis=0)
print(out.shape)
out

(6, 4)


array([[100, 101, 102, 103],
       [110, 111, 112, 113],
       [120, 121, 122, 123],
       [200, 201, 202, 203],
       [210, 211, 212, 213],
       [220, 221, 222, 223]])

In [106]:
out = np.concatenate((a, b), axis=1)
print(out.shape)
out

(3, 8)


array([[100, 101, 102, 103, 200, 201, 202, 203],
       [110, 111, 112, 113, 210, 211, 212, 213],
       [120, 121, 122, 123, 220, 221, 222, 223]])

### hstack(tup)
Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis. Rebuilds arrays divided by hsplit.

This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general stacking and concatenation operations.

In [28]:
a = np.array([1, 2, 3])
b = np.array((2, 3, 4))
print (a.shape)

(3,)


In [25]:
out = np.hstack((a, b))
print(out.shape)
out

(6,)


array([1, 2, 3, 2, 3, 4])

In [26]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print (a.shape)
print (a)
print (b)

(3, 1)
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


In [27]:
out = np.hstack((a, b))
print(out.shape)
out

(3, 2)


array([[1, 2],
       [2, 3],
       [3, 4]])

In [82]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [84]:
print (np.hstack((a, b)).shape)
np.hstack((a, b))

(3, 8)


array([[100, 101, 102, 103, 200, 201, 202, 203],
       [110, 111, 112, 113, 210, 211, 212, 213],
       [120, 121, 122, 123, 220, 221, 222, 223]])

### vstack(tup)
Stack arrays in sequence vertically (row wise)

This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.

This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general stacking and concatenation operations.

In [29]:
a = np.array([1, 2, 3])
b = np.array((2, 3, 4))
print (a.shape)

(3,)


In [30]:
out = np.vstack((a, b))
print(out.shape)
out

(2, 3)


array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(a.shape)

(3, 1)


In [32]:
out = np.vstack((a, b))
print(out.shape)
out

(6, 1)


array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [85]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [86]:
print (np.vstack((a, b)).shape)
np.vstack((a, b))

(6, 4)


array([[100, 101, 102, 103],
       [110, 111, 112, 113],
       [120, 121, 122, 123],
       [200, 201, 202, 203],
       [210, 211, 212, 213],
       [220, 221, 222, 223]])

### dstack(tup)
Stack arrays in sequence depth wise (along third axis)

This is equivalent to concatenation along the third axis after 2-D arrays of shape (M,N) have been reshaped to (M,N,1) and 1-D arrays of shape (N,) have been reshaped to (1,N,1). Rebuilds arrays divided by dsplit.

This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general stacking and concatenation operations.

In [37]:
a = np.array((1, 2, 3))
b = np.array((2, 3, 4))
print (a.shape)

(3,)


In [38]:
out = np.dstack((a, b))
print(out.shape)
out

(1, 3, 2)


array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [40]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print (a.shape)

(3, 1)


In [41]:
out = np.dstack((a, b))
print(out.shape)
out

(3, 1, 2)


array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [87]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [89]:
print (np.dstack((a, b)).shape)
np.dstack((a, b))

(3, 4, 2)


array([[[100, 200],
        [101, 201],
        [102, 202],
        [103, 203]],

       [[110, 210],
        [111, 211],
        [112, 212],
        [113, 213]],

       [[120, 220],
        [121, 221],
        [122, 222],
        [123, 223]]])

### column_stack(tup)
Stack 1-D arrays as columns into a 2-D array

Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack. 1-D arrays are turned into 2-D columns first.

In [42]:
a = np.array([1, 2, 3])
b = np.array((2, 3, 4))
print (a.shape)

(3,)


In [43]:
out = np.column_stack((a, b))
print(out.shape)
out

(3, 2)


array([[1, 2],
       [2, 3],
       [3, 4]])

In [91]:
a = np.array([[100, 101, 102, 103],
              [110, 111, 112, 113],
              [120, 121, 122, 123]])

b = np.array([[200, 201, 202, 203],
              [210, 211, 212, 213],
              [220, 221, 222, 223]])
print (a.shape)

(3, 4)


In [92]:
print (np.column_stack((a, b)).shape)
np.column_stack((a, b))

(3, 8)


array([[100, 101, 102, 103, 200, 201, 202, 203],
       [110, 111, 112, 113, 210, 211, 212, 213],
       [120, 121, 122, 123, 220, 221, 222, 223]])

### resize(a, new_shape)
Return a new array with the specified shape.

If the new array is larger than the original array, then the new array is filled with repeated copies of a. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a

In [5]:
a = np.arange(0, 4).reshape(2, 2)
print (a)

[[0 1]
 [2 3]]


In [6]:
np.resize(a, (2, 3))

array([[0, 1, 2],
       [3, 0, 1]])

In [7]:
np.resize(a, (1, 5))

array([[0, 1, 2, 3, 0]])

### tile(A, reps)
Construct an array by repeating A the number of times given by reps.

In [10]:
a = np.arange(0, 3)
print (a)

[0 1 2]


In [11]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [12]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [13]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [18]:
b = np.arange(1, 5).reshape((2, 2))
print (b)

[[1 2]
 [3 4]]


In [19]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [20]:
np.tile(b, (2, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [21]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [22]:
np.tile(b, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

### repeat(a, repeats, axis=None)
Repeat elements of an array

In [24]:
np.repeat(3, 4, axis=0)

array([3, 3, 3, 3])

In [26]:
x = np.arange(1, 5).reshape(2, 2)
print (x)

[[1 2]
 [3 4]]


In [27]:
np.repeat(x, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [28]:
np.repeat(x, 2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [34]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])